-- Por qué: renovación del área de Salud mental (lote: psiquiatria + psicologia). Las plantillas
-- de fábrica de estas dos especialidades salían del generador genérico del catálogo y no pedían
-- lo que define una nota de salud mental: examen mental por dominios tal como lo describió el
-- profesional, evaluación del riesgo en sus palabras (la IA nunca puntúa escalas ni clasifica el
-- riesgo por su cuenta), adherencia y efectos adversos de psicofármacos transcritos literal, y
-- lenguaje respetuoso y no estigmatizante en un documento médico-legal sensible.
--
-- psiquiatria: "Consulta inicial · historia psiquiátrica y examen mental", "Control y seguimiento · estado mental, adherencia y riesgo", "Valoración psiquiátrica · interconsulta y concepto especializado", "Urgencia psiquiátrica · riesgo suicida y agitación" — 4ª fijada por el encargo: es la atención de mayor riesgo documental de la especialidad.
-- psicologia: "Consulta inicial · motivo, contexto y recursos de afrontamiento", "Control y seguimiento · objetivos terapéuticos y evolución", "Valoración psicológica · concepto y recomendaciones", "Intervención en crisis · contención y plan de seguridad" — 4ª elegida: la crisis no programada es el escenario de mayor riesgo documental del psicólogo (señales de riesgo, plan de seguridad, activación de ruta) y no lo cubren las otras tres.

update public.clinical_templates set
  name = 'Consulta inicial · historia psiquiátrica y examen mental',
  description = 'Primera valoración psiquiátrica ambulatoria: motivo en palabras del paciente, historia de la enfermedad actual, consumo de sustancias, contexto psicosocial, examen mental completo, evaluación del riesgo y plan con psicofármacos transcritos literal.',
  sections = '[
    {"key":"motivo_de_consulta","label":"Motivo de consulta","order":1,"required":true,"instruction":"Registra el motivo en las palabras del paciente y, si aplica, de quien lo acompaña; anota quién solicita la atención (voluntad propia, familia, remisión de EPS u otro servicio). No lo traduzcas a un diagnóstico ni añadas interpretaciones que no se dijeron."},
    {"key":"enfermedad_actual","label":"Enfermedad actual","order":2,"required":false,"instruction":"Cronología del episodio: inicio, duración y evolución de los síntomas afectivos, ansiosos, psicóticos o del comportamiento que el médico describió; sueño, apetito, energía, impacto en el funcionamiento diario y estresores mencionados. Solo lo dicho en la consulta; si algo no se exploró, indícalo."},
    {"key":"antecedentes_psiquiatricos","label":"Antecedentes psiquiátricos","order":3,"required":false,"instruction":"Episodios previos, hospitalizaciones psiquiátricas, intentos de suicidio o autolesiones anteriores tal como el médico los consignó, tratamientos recibidos (fármacos y psicoterapia) y respuesta a cada uno. Si no se habló de antecedentes, indícalo; no completes con supuestos."},
    {"key":"consumo_de_sustancias","label":"Consumo de sustancias","order":4,"required":false,"instruction":"Alcohol, tabaco, cannabis u otras sustancias: tipo, patrón, cantidad y último consumo únicamente con los datos que se dijeron. Incluye intentos de abandono o tratamientos previos si se mencionaron. Si el tema no se abordó, escríbelo así; nunca estimes cantidades ni frecuencias."},
    {"key":"antecedentes_medicos_y_familiares","label":"Antecedentes médicos y familiares","order":5,"required":false,"instruction":"Enfermedades médicas, medicación actual con dosis transcrita literal (nunca la deduzcas), alergias y antecedentes familiares psiquiátricos, incluidos suicidios en la familia solo si el médico los mencionó. Lo no preguntado se registra como no explorado."},
    {"key":"contexto_psicosocial_y_funcionamiento","label":"Contexto psicosocial y funcionamiento","order":6,"required":false,"instruction":"Ocupación, estudio, convivencia, relaciones significativas, red de apoyo, situación económica o legal y eventos vitales recientes que se hayan comentado, junto con el nivel de funcionamiento descrito. Usa lenguaje respetuoso y no estigmatizante; solo lo mencionado."},
    {"key":"examen_mental","label":"Examen mental","order":7,"required":true,"instruction":"Apariencia, actitud, conciencia y orientación, atención, lenguaje, afecto y ánimo, curso y contenido del pensamiento, sensopercepción, memoria, juicio e introspección, tal como el médico los describió. No completes dominios no explorados ni uses términos que él no empleó; si un dominio no se mencionó, indícalo."},
    {"key":"evaluacion_del_riesgo","label":"Evaluación del riesgo","order":8,"required":true,"instruction":"Ideación o conducta suicida, autolesiva o heteroagresiva únicamente en las palabras del médico: presencia o ausencia, plan, medios y factores protectores que él haya enunciado. Si dictó una escala con su puntaje, transcríbelo literal; nunca puntúes escalas ni clasifiques el nivel de riesgo por tu cuenta."},
    {"key":"analisis_e_impresion_diagnostica","label":"Análisis e impresión diagnóstica","order":9,"required":true,"instruction":"Razonamiento clínico y diagnósticos con la precisión con que el médico los formuló, incluidos episodios, especificadores o diferenciales solo si él los enunció. No agregues códigos ni categorías diagnósticas que no se dijeron."},
    {"key":"plan_de_manejo_y_proximo_control","label":"Plan de manejo y próximo control","order":10,"required":true,"instruction":"Psicofármacos con nombre, dosis, frecuencia y duración transcritos literal, sin recalcular ni completar lo que falte; psicoterapia indicada, paraclínicos, remisiones, incapacidad si se mencionó, psicoeducación dada al paciente y la familia, fecha del próximo control y signos de alarma explicados."}
  ]'::jsonb,
  updated_at = now()
where id = '63a961ff-aad8-5422-b1a8-406b18d00793' and owner_id is null;

update public.clinical_templates set
  name = 'Control y seguimiento · estado mental, adherencia y riesgo',
  description = 'Control ambulatorio de un paciente con proceso psiquiátrico en curso: evolución del episodio, adherencia y efectos adversos de los psicofármacos, examen mental de control, reevaluación del riesgo y ajuste del plan.',
  sections = '[
    {"key":"diagnosticos_activos_y_evolucion","label":"Diagnósticos activos y tiempo de evolución","order":1,"required":true,"instruction":"Diagnósticos psiquiátricos en manejo y tiempo de evolución tal como el médico los recordó en la consulta, junto con el tratamiento actual descrito. No agregues diagnósticos de notas previas que no se hayan mencionado hoy."},
    {"key":"evolucion_desde_el_ultimo_control","label":"Evolución desde el último control","order":2,"required":false,"instruction":"Intervalo desde la última cita y cambios en los síntomas afectivos, ansiosos o psicóticos, sueño, apetito, funcionamiento diario y eventos relevantes (crisis, urgencias, hospitalizaciones) que el paciente o el médico refirieron. Solo lo dicho; si un aspecto no se exploró, indícalo."},
    {"key":"adherencia_y_efectos_adversos","label":"Adherencia y efectos adversos","order":3,"required":false,"instruction":"Adherencia al tratamiento en las palabras del paciente (dosis omitidas y motivos) y efectos adversos referidos: sedación, aumento de peso, síntomas extrapiramidales, disfunción sexual u otros, tal como se describieron. Los nombres y dosis de los fármacos se transcriben literal; nunca los completes ni los corrijas."},
    {"key":"resultados_de_paraclinicos","label":"Resultados de paraclínicos y niveles","order":4,"required":false,"instruction":"Laboratorios, niveles séricos u otros paraclínicos revisados hoy, con los valores exactos que el médico dictó: transcríbelos literal, nunca los estimes ni los interpretes por tu cuenta. Si no se revisaron resultados, indícalo."},
    {"key":"examen_mental_de_control","label":"Examen mental de control","order":5,"required":true,"instruction":"Examen mental dirigido de la cita: apariencia, actitud, afecto y ánimo, curso y contenido del pensamiento, sensopercepción, juicio e introspección, con los términos exactos que el médico empleó. No repitas el examen de citas anteriores ni completes dominios que hoy no se describieron."},
    {"key":"evaluacion_del_riesgo","label":"Evaluación del riesgo","order":6,"required":true,"instruction":"Reevaluación de ideación suicida, autolesiva o heteroagresiva en las palabras del médico, incluidos cambios frente al control anterior si él los comentó. Escalas solo si las dictó con su puntaje: transcríbelo literal; nunca puntúes ni clasifiques el riesgo por tu cuenta. Si el tema no se abordó, indícalo."},
    {"key":"analisis_y_metas_terapeuticas","label":"Análisis y metas terapéuticas","order":7,"required":true,"instruction":"Evaluación del médico sobre la respuesta al tratamiento (remisión, respuesta parcial, recaída u otra formulación que él haya usado) y el avance frente a las metas del proceso: síntomas, funcionamiento, retorno laboral o académico. Solo las conclusiones que él enunció."},
    {"key":"ajuste_del_plan","label":"Ajuste del plan","order":8,"required":true,"instruction":"Cambios de medicación con nombre, dosis, frecuencia y titulación transcritos literal, sin recalcular; continuidad de psicoterapia, paraclínicos solicitados, remisiones, incapacidad o certificados si se mencionaron y la psicoeducación dada. Registra que el manejo continúa igual solo si el médico lo dijo."},
    {"key":"proximo_control_y_signos_de_alarma","label":"Próximo control y signos de alarma","order":9,"required":false,"instruction":"Fecha o plazo del próximo control y los signos de alarma explicados al paciente y su red de apoyo para consultar antes (empeoramiento del ánimo, ideación suicida, efectos adversos importantes, abandono del tratamiento). Solo lo que se explicó en la consulta."}
  ]'::jsonb,
  updated_at = now()
where id = '34d36e1f-fbf1-58e9-814f-c2f0ce23f0ab' and owner_id is null;

update public.clinical_templates set
  name = 'Valoración psiquiátrica · interconsulta y concepto especializado',
  description = 'Valoración solicitada por otro servicio, EPS o entidad: pregunta de la interconsulta, contexto clínico, examen mental, riesgo y concepto con recomendaciones para el equipo tratante. Úsala cuando la cita responde a una remisión y debe emitirse un concepto.',
  sections = '[
    {"key":"motivo_de_la_valoracion","label":"Motivo de la valoración","order":1,"required":true,"instruction":"Registra quién solicita la valoración (servicio hospitalario, médico tratante, EPS, medicina laboral) y la pregunta específica que se pide responder, tal como quedó planteada en la consulta. No amplíes el alcance de la solicitud."},
    {"key":"contexto_clinico_actual","label":"Contexto clínico actual","order":2,"required":false,"instruction":"Enfermedad o situación de base que motiva la interconsulta, hospitalización o tratamiento en curso y medicamentos actuales con dosis transcrita literal si se mencionaron. Solo la información disponible en la consulta; no la completes desde suposiciones."},
    {"key":"antecedentes_psiquiatricos_relevantes","label":"Antecedentes psiquiátricos relevantes","order":3,"required":false,"instruction":"Historia psiquiátrica pertinente a la pregunta: episodios, hospitalizaciones, intentos de suicidio, tratamientos y respuesta, consumo de sustancias, tal como el médico los consignó. Si no hay antecedentes o no se exploraron, dilo explícitamente."},
    {"key":"entrevista_y_actitud","label":"Entrevista y actitud frente a la valoración","order":4,"required":false,"instruction":"Relato del paciente durante la entrevista, su disposición a colaborar y su comprensión de la situación, descritos con lenguaje respetuoso y no estigmatizante. Registra únicamente lo observado y dicho en la sesión."},
    {"key":"examen_mental","label":"Examen mental","order":5,"required":true,"instruction":"Apariencia, actitud, conciencia y orientación, afecto y ánimo, curso y contenido del pensamiento, sensopercepción, memoria, juicio e introspección con los términos exactos del médico. No completes dominios no explorados; si alguno no se describió, indícalo."},
    {"key":"evaluacion_del_riesgo","label":"Evaluación del riesgo","order":6,"required":true,"instruction":"Riesgo suicida, autolesivo o heteroagresivo únicamente en las palabras del médico, con los factores que él haya enunciado. Escalas solo si las dictó con su puntaje: transcríbelo literal; nunca puntúes ni clasifiques el nivel de riesgo por tu cuenta."},
    {"key":"concepto_e_impresion_diagnostica","label":"Concepto e impresión diagnóstica","order":7,"required":true,"instruction":"Concepto psiquiátrico que responde la pregunta de la interconsulta y diagnósticos con la precisión con que el médico los formuló, incluida la capacidad del paciente para decidir sobre su tratamiento solo si él se pronunció al respecto. No agregues conclusiones que no se dijeron."},
    {"key":"recomendaciones_y_seguimiento","label":"Recomendaciones y seguimiento","order":8,"required":true,"instruction":"Recomendaciones para el servicio o entidad solicitante: manejo farmacológico transcrito literal (nombre, dosis, frecuencia), medidas de cuidado, necesidad de traslado, hospitalización o seguimiento por psiquiatría, y condiciones para nueva valoración, solo según lo indicado en la consulta."}
  ]'::jsonb,
  updated_at = now()
where id = 'e4086bdf-27ec-5fe0-8c74-49eae824ea81' and owner_id is null;

insert into public.clinical_templates
  (id, owner_id, name, description, specialty_code, specialty_name, scope, is_default, status, sections)
values
  ('c5000000-0000-4000-8000-000000000001', null,
   'Urgencia psiquiátrica · riesgo suicida y agitación',
   'Atención de urgencia por crisis suicida, agitación u otra descompensación aguda: desencadenante, examen mental, riesgo en palabras del médico, medidas de seguridad, manejo farmacológico literal y plan de contención. Úsala en urgencias u observación, no en consulta programada.',
   'psiquiatria', 'Psiquiatría', 'institutional', false, 'active',
   '[
    {"key":"motivo_y_desencadenante","label":"Motivo de atención y desencadenante","order":1,"required":true,"instruction":"Motivo de la atención de urgencia, desencadenante y contexto inmediato: quién trae al paciente, cómo llega (remitido, traído por familia, policía o ambulancia) y qué ocurrió según lo relatado. Usa las palabras de la consulta, con lenguaje respetuoso; no reconstruyas hechos que nadie relató."},
    {"key":"relato_del_episodio","label":"Relato del episodio actual","order":2,"required":false,"instruction":"Cronología del episodio: ideación, plan, método o intento tal como el médico lo consignó, conducta agitada o agresiva descrita, consumo reciente de sustancias y tiempo transcurrido. Transcribe los detalles exactos que se dijeron; no agregues métodos, cantidades ni circunstancias no mencionadas."},
    {"key":"antecedentes_relevantes","label":"Antecedentes relevantes","order":3,"required":false,"instruction":"Intentos de suicidio u hospitalizaciones previas, diagnóstico psiquiátrico de base, tratamiento actual con dosis transcrita literal, consumo de sustancias y enfermedades médicas, solo si se mencionaron en la atención. Lo no explorado se registra como tal."},
    {"key":"examen_fisico_y_signos_vitales","label":"Examen físico y signos vitales","order":4,"required":false,"instruction":"Signos vitales con los valores dichos, lesiones externas (heridas, laceraciones, signos de intoxicación) y hallazgos físicos relevantes descritos por el médico. Nunca inventes cifras ni hallazgos; si el examen físico no se realizó o no se describió, indícalo."},
    {"key":"examen_mental_completo","label":"Examen mental completo","order":5,"required":true,"instruction":"Apariencia, actitud, conciencia y orientación, atención, lenguaje, afecto y ánimo, curso y contenido del pensamiento, sensopercepción, memoria, juicio e introspección tal como el médico los describió en la urgencia. No completes dominios no explorados ni suavices ni exageres los términos que él usó."},
    {"key":"evaluacion_del_riesgo","label":"Evaluación del riesgo suicida y heteroagresivo","order":6,"required":true,"instruction":"Evaluación del riesgo suicida y heteroagresivo estrictamente en las palabras del médico: ideación, plan, acceso a medios, factores protectores y su conclusión sobre el riesgo si la enunció. Escalas solo si las dictó con su puntaje: transcríbelo literal; nunca puntúes escalas ni clasifiques el nivel de riesgo por tu cuenta."},
    {"key":"medidas_de_seguridad","label":"Medidas de seguridad tomadas","order":7,"required":false,"instruction":"Medidas de seguridad implementadas durante la atención tal como se describieron: acompañamiento permanente, retiro de objetos de riesgo, observación, contención física o verbal con su justificación y duración si el médico las consignó. Registra solo las medidas efectivamente mencionadas."},
    {"key":"manejo_farmacologico","label":"Manejo farmacológico en urgencia","order":8,"required":false,"instruction":"Medicamentos administrados o formulados en la urgencia con nombre, dosis, vía y hora transcritos literal, sin recalcular ni completar datos faltantes, y la respuesta observada si se describió. Si no se usó medicación, escríbelo así."},
    {"key":"impresion_diagnostica","label":"Impresión diagnóstica","order":9,"required":true,"instruction":"Impresión diagnóstica del episodio con la precisión con que el médico la formuló (episodio, trastorno de base, intoxicación asociada u otra formulación suya). Incluye diferenciales solo si los enunció; no agregues diagnósticos ni códigos por tu cuenta."},
    {"key":"red_de_apoyo_y_acuerdos","label":"Red de apoyo y acuerdos","order":10,"required":false,"instruction":"Familiares o acompañantes presentes, quién asume el acompañamiento y los acuerdos establecidos con el paciente y su red: retiro de medios letales en casa, acompañamiento permanente, compromisos de consulta. Solo los acuerdos que realmente se verbalizaron en la atención."},
    {"key":"plan_de_contencion_y_seguimiento","label":"Plan de contención y seguimiento","order":11,"required":true,"instruction":"Conducta definida: hospitalización, remisión (a psiquiatría, unidad de salud mental o mediante la EPS), observación o alta con plan de seguridad, tal como el médico la indicó. Incluye controles, líneas de atención de crisis mencionadas y signos de alarma explicados a la red de apoyo. No añadas conductas no dichas."}
   ]'::jsonb)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  specialty_code = excluded.specialty_code,
  specialty_name = excluded.specialty_name,
  sections = excluded.sections,
  updated_at = now();

update public.clinical_templates set
  name = 'Consulta inicial · motivo, contexto y recursos de afrontamiento',
  description = 'Primera consulta de psicología clínica: motivo en palabras del consultante, historia del problema, contexto y red de apoyo, recursos de afrontamiento, observaciones en sesión e hipótesis de trabajo con el encuadre del proceso.',
  sections = '[
    {"key":"motivo_de_consulta","label":"Motivo de consulta","order":1,"required":true,"instruction":"Registra el motivo en las palabras del consultante y cómo llega al servicio (voluntad propia, remisión de EPS, psiquiatría, colegio o empresa). No lo traduzcas a categorías diagnósticas ni a lenguaje técnico que la persona no usó."},
    {"key":"historia_del_problema","label":"Historia del problema actual","order":2,"required":false,"instruction":"Inicio, evolución y situaciones que agravan o alivian el problema, con el impacto descrito en las áreas laboral, académica, familiar y de pareja. Solo lo relatado en sesión; si un área no se exploró, indícalo en lugar de completarla."},
    {"key":"antecedentes_de_atencion_y_salud","label":"Antecedentes de atención y salud","order":3,"required":false,"instruction":"Procesos psicológicos o psiquiátricos previos y su resultado según el consultante, medicación actual transcrita literal si se mencionó (nunca la completes), condiciones médicas relevantes y consumo de sustancias solo si se habló de ello."},
    {"key":"historia_personal_y_familiar","label":"Historia personal y familiar","order":4,"required":false,"instruction":"Historia personal y familiar relevante al motivo: composición y dinámica familiar, relaciones significativas, eventos vitales y pérdidas que el consultante haya relatado. Usa lenguaje respetuoso y no estigmatizante; registra solo lo dicho en sesión."},
    {"key":"contexto_actual_y_red_de_apoyo","label":"Contexto actual y red de apoyo","order":5,"required":false,"instruction":"Ocupación o estudio, convivencia actual, red de apoyo disponible y situaciones de contexto (económicas, legales, de cuidado) mencionadas en sesión. No infieras la calidad de la red de apoyo; describe la que el consultante refirió."},
    {"key":"recursos_de_afrontamiento","label":"Recursos y estrategias de afrontamiento","order":6,"required":false,"instruction":"Estrategias que la persona usa para afrontar el problema, fortalezas, intereses y motivación al cambio, tal como aparecieron en la conversación. Registra también las estrategias que el consultante describe como poco útiles, sin juzgarlas."},
    {"key":"observaciones_en_sesion","label":"Observaciones conductuales en sesión","order":7,"required":true,"instruction":"Observaciones del profesional durante la sesión: presentación, actitud, discurso, expresión emocional y contacto, con los términos que él empleó. Instrumentos o tamizajes (por ejemplo PHQ-9 o GAD-7) solo si el profesional los dictó con su puntaje: transcríbelo literal, nunca lo calcules tú."},
    {"key":"analisis_e_hipotesis_de_trabajo","label":"Análisis e hipótesis de trabajo","order":8,"required":true,"instruction":"Hipótesis inicial y comprensión del caso tal como el profesional las formuló, incluido el enfoque desde el que planea trabajar solo si lo enunció. No conviertas la hipótesis en diagnóstico ni agregues etiquetas clínicas que no se dijeron."},
    {"key":"plan_y_encuadre","label":"Plan terapéutico y encuadre acordado","order":9,"required":true,"instruction":"Plan acordado con el consultante: objetivos iniciales, frecuencia y modalidad de las sesiones, tareas entre sesiones, remisión a psiquiatría u otro servicio si se mencionó y acuerdos de confidencialidad explicados. Solo los acuerdos que quedaron verbalizados en sesión."}
  ]'::jsonb,
  updated_at = now()
where id = '2037baa1-d738-5bdc-a378-114dc1991d95' and owner_id is null;

update public.clinical_templates set
  name = 'Control y seguimiento · objetivos terapéuticos y evolución',
  description = 'Sesión de seguimiento dentro de un proceso ya iniciado: foco de la sesión, evolución desde la última cita, intervenciones aplicadas, avances frente a los objetivos y tareas acordadas. Úsala para las sesiones intermedias del proceso terapéutico.',
  sections = '[
    {"key":"foco_de_la_sesion","label":"Foco de la sesión y objetivos del proceso","order":1,"required":true,"instruction":"Objetivos del proceso que se retomaron y el tema central que el consultante trajo hoy, en sus palabras. No asumas continuidad con sesiones previas que no se haya mencionado en esta sesión."},
    {"key":"evolucion_desde_la_ultima_sesion","label":"Evolución desde la última sesión","order":2,"required":false,"instruction":"Cambios desde la última sesión: estado emocional referido, situaciones significativas, cumplimiento de las tareas acordadas y dificultades para realizarlas, tal como el consultante lo relató. Si las tareas no se revisaron, indícalo."},
    {"key":"estado_emocional_reportado","label":"Estado emocional y malestar reportado","order":3,"required":false,"instruction":"Estado emocional y nivel de malestar descritos por el consultante en sus palabras. Escalas o autorregistros solo si el profesional los dictó con su valor: transcríbelo literal, nunca lo calcules ni lo estimes tú. Si no se usó ninguna medida, no la agregues."},
    {"key":"observaciones_en_sesion","label":"Observaciones del profesional en sesión","order":4,"required":true,"instruction":"Observaciones conductuales del profesional: actitud, discurso, expresión emocional, contacto y cambios frente a sesiones previas que él haya señalado, con sus términos exactos. No completes con impresiones que no fueron enunciadas."},
    {"key":"intervenciones_realizadas","label":"Intervenciones y técnicas trabajadas","order":5,"required":false,"instruction":"Técnicas e intervenciones aplicadas en la sesión únicamente si el profesional las nombró (por ejemplo reestructuración cognitiva, activación conductual, exposición, entrenamiento en respiración) y la respuesta del consultante a cada una. No atribuyas técnicas ni enfoques no mencionados."},
    {"key":"avances_y_dificultades","label":"Avances y dificultades frente a los objetivos","order":6,"required":true,"instruction":"Valoración del profesional sobre el avance frente a los objetivos terapéuticos: logros, estancamientos o retrocesos tal como él los formuló. Incluye señales de riesgo solo si se mencionaron y en las palabras del profesional; nunca clasifiques el riesgo por tu cuenta."},
    {"key":"tareas_y_acuerdos","label":"Tareas y acuerdos para la próxima sesión","order":7,"required":true,"instruction":"Tareas entre sesiones y acuerdos verbalizados: qué hará el consultante, ajustes del plan, coordinación con psiquiatría u otro servicio si se mencionó (remisión, trámite por la EPS). Registra solo los compromisos que efectivamente se acordaron en sesión."},
    {"key":"proxima_sesion","label":"Próxima sesión","order":8,"required":false,"instruction":"Fecha o plazo acordado para la próxima sesión y las condiciones para consultar antes (líneas de crisis o urgencias solo si se explicaron en sesión). Si no se fijó fecha, regístralo así."}
  ]'::jsonb,
  updated_at = now()
where id = 'eda731a7-4cc5-599b-be91-7bd5cf4a737d' and owner_id is null;

update public.clinical_templates set
  name = 'Valoración psicológica · concepto y recomendaciones',
  description = 'Valoración solicitada por un tercero (EPS, colegio, empresa, psiquiatría u otro profesional): pregunta de la remisión, entrevista, instrumentos aplicados con puntajes literales, concepto y recomendaciones. Úsala cuando debe emitirse un concepto sin iniciar proceso terapéutico.',
  sections = '[
    {"key":"motivo_de_la_valoracion","label":"Motivo de la valoración","order":1,"required":true,"instruction":"Registra quién solicita la valoración (EPS, colegio, empresa, psiquiatría, otro profesional) y la pregunta específica que se pide responder, tal como quedó planteada. No amplíes el alcance de la solicitud ni respondas preguntas que no se hicieron."},
    {"key":"contexto_y_antecedentes","label":"Contexto y antecedentes relevantes","order":2,"required":false,"instruction":"Contexto del consultante pertinente a la pregunta: situación actual, antecedentes de atención en salud mental, medicación transcrita literal si se mencionó y eventos relevantes relatados en la entrevista. Lo no explorado se registra como tal."},
    {"key":"entrevista_y_relato","label":"Entrevista y relato del consultante","order":3,"required":false,"instruction":"Relato del consultante durante la entrevista y su disposición frente a la valoración, en lenguaje respetuoso y no estigmatizante. Diferencia lo que la persona relató de lo que informaron terceros, y registra solo lo dicho en la sesión."},
    {"key":"instrumentos_aplicados","label":"Instrumentos y pruebas aplicadas","order":4,"required":false,"instruction":"Pruebas o instrumentos aplicados únicamente si el profesional los nombró, con los puntajes o resultados exactos que dictó: transcríbelos literal, nunca los calcules, interpretes ni conviertas a percentiles por tu cuenta. Si no se aplicaron instrumentos, indícalo."},
    {"key":"observaciones_conductuales","label":"Observaciones conductuales","order":5,"required":true,"instruction":"Observaciones del profesional durante la valoración: presentación, actitud, discurso, expresión emocional, atención y colaboración, con los términos exactos que empleó. No completes con conductas no descritas."},
    {"key":"analisis_y_concepto","label":"Análisis y concepto profesional","order":6,"required":true,"instruction":"Concepto que responde la pregunta de la valoración tal como el profesional lo formuló, con las hipótesis o conclusiones que enunció. No conviertas el concepto en diagnóstico psiquiátrico ni agregues etiquetas que no se dijeron."},
    {"key":"recomendaciones_y_remision","label":"Recomendaciones y remisión","order":7,"required":true,"instruction":"Recomendaciones para el solicitante y el consultante: inicio de proceso terapéutico, remisión a psiquiatría u otro servicio mediante la EPS, ajustes escolares o laborales, todo únicamente según lo indicado en la sesión. No agregues recomendaciones estándar no verbalizadas."},
    {"key":"seguimiento_acordado","label":"Seguimiento acordado","order":8,"required":false,"instruction":"Cierre de la valoración: si queda con seguimiento, con quién y en qué plazo, y los compromisos verbalizados con el consultante o el solicitante. Si la valoración termina sin seguimiento, regístralo así."}
  ]'::jsonb,
  updated_at = now()
where id = '100d53d3-2057-5618-a27f-b8bac1a985ce' and owner_id is null;

insert into public.clinical_templates
  (id, owner_id, name, description, specialty_code, specialty_name, scope, is_default, status, sections)
values
  ('c5000000-0000-4000-8000-000000000002', null,
   'Intervención en crisis · contención y plan de seguridad',
   'Atención no programada de una crisis emocional, con o sin señales de riesgo: desencadenante, estado del consultante, contención realizada, plan de seguridad acordado, red de apoyo y activación de ruta (urgencias, psiquiatría, EPS). Úsala cuando la sesión se convierte en manejo de crisis.',
   'psicologia', 'Psicología clínica', 'institutional', false, 'active',
   '[
    {"key":"situacion_de_crisis_y_desencadenante","label":"Situación de crisis y desencadenante","order":1,"required":true,"instruction":"Describe la situación de crisis y su desencadenante tal como se relató: qué ocurrió, cuándo y cómo llega el consultante a la atención (presencial, llamada, acompañado o solo). Usa lenguaje respetuoso; no reconstruyas hechos que nadie relató."},
    {"key":"relato_y_estado_emocional","label":"Relato y estado emocional del consultante","order":2,"required":false,"instruction":"Relato del consultante en sus palabras y el estado emocional observado por el profesional durante la atención (llanto, agitación, bloqueo, calma progresiva), con los términos que él empleó. Solo lo dicho y observado en esta atención."},
    {"key":"antecedentes_inmediatos","label":"Antecedentes inmediatos relevantes","order":3,"required":false,"instruction":"Antecedentes pertinentes a la crisis solo si se mencionaron: crisis o intentos previos, proceso terapéutico en curso, atención psiquiátrica, medicación transcrita literal y consumo reciente de sustancias. Lo no explorado se registra como tal."},
    {"key":"senales_de_riesgo","label":"Señales de riesgo identificadas","order":4,"required":true,"instruction":"Expresiones de ideación suicida, autolesión, desesperanza o riesgo para terceros estrictamente en las palabras con que el profesional las consignó, incluidos plan o acceso a medios si se mencionaron. Nunca puntúes escalas ni clasifiques el nivel de riesgo por tu cuenta; si no se identificaron señales, dilo explícitamente."},
    {"key":"contencion_realizada","label":"Intervención y contención realizada","order":5,"required":true,"instruction":"Intervenciones de contención aplicadas durante la atención únicamente si el profesional las nombró (estabilización emocional, respiración, anclaje, escucha activa, psicoeducación sobre la crisis) y la respuesta del consultante a cada una. No atribuyas técnicas no mencionadas."},
    {"key":"plan_de_seguridad","label":"Plan de seguridad acordado","order":6,"required":true,"instruction":"Plan de seguridad construido con el consultante tal como quedó verbalizado: señales de alerta personales, estrategias de afrontamiento, personas y líneas de contacto, retiro o restricción de medios y compromisos asumidos. Registra solo los elementos que realmente se acordaron; no completes un plan estándar."},
    {"key":"red_de_apoyo_activada","label":"Red de apoyo y acompañamiento","order":7,"required":false,"instruction":"Personas de la red de apoyo contactadas o presentes, qué se les explicó y quién asume el acompañamiento del consultante después de la atención, según lo dicho en la sesión. Si no fue posible activar la red, indícalo."},
    {"key":"remision_y_activacion_de_ruta","label":"Remisión y activación de ruta","order":8,"required":false,"instruction":"Remisiones o activación de ruta realizadas: urgencias, psiquiatría, línea de crisis o trámite por la EPS, tal como el profesional lo indicó, con los datos que dio. No agregues rutas, líneas ni entidades que no se mencionaron en la atención."},
    {"key":"seguimiento_acordado","label":"Seguimiento acordado","order":9,"required":false,"instruction":"Seguimiento pactado tras la crisis: próxima cita o contacto, en qué plazo y por qué medio, y las condiciones acordadas para consultar de inmediato. Solo los compromisos verbalizados al cierre de la atención."}
   ]'::jsonb)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  specialty_code = excluded.specialty_code,
  specialty_name = excluded.specialty_name,
  sections = excluded.sections,
  updated_at = now();
