-- Por qué: renovación del área 7 del catálogo (medicina física y rehabilitación + dolor y
-- cuidados paliativos). Las plantillas de fábrica eran genéricas: no pedían funcionalidad previa
-- y actual, ayudas técnicas ni metas en rehabilitación, ni transcripción literal de opioides,
-- esfera emocional-espiritual o conversación de metas de cuidado en paliativos. Se reescriben
-- las 3 de fábrica de cada especialidad y se agrega una 4ª nueva por especialidad.
--
-- rehabilitacion: Consulta inicial · valoración funcional y plan de rehabilitación | Control y seguimiento · metas funcionales y respuesta al plan | Procedimiento · intervenciones en rehabilitación (infiltración, toxina botulínica) | Prescripción de plan terapéutico · terapia física y ocupacional con metas — la 4ª porque formular o renovar terapias con metas funcionales y trámites ante la EPS es la cita más frecuente del fisiatra y no la cubrían las otras 3.
-- dolor_paliativos: Consulta inicial · valoración integral de dolor y síntomas | Control y seguimiento · alivio del dolor y ajuste de analgesia | Procedimiento · intervencionismo analgésico y de confort | Valoración de fin de vida · voluntades anticipadas y plan de confort — la 4ª porque el fin de vida es el momento de mayor riesgo documental del servicio: dejar constancia digna de las decisiones acordadas y del plan de confort.

update public.clinical_templates set
  name = 'Consulta inicial · valoración funcional y plan de rehabilitación',
  description = 'Primera valoración por fisiatría: funcionalidad previa y actual, examen neuromusculoesquelético, escalas solo si se aplicaron y formulación del plan de rehabilitación con metas funcionales. Úsala cuando el paciente llega remitido o consulta por primera vez por una condición que limita su función.',
  sections = '[
    {"key":"motivo_de_consulta_y_remision","label":"Motivo de consulta y remisión","order":1,"required":true,"instruction":"Documenta el motivo en las palabras del paciente o su acompañante y quién lo remite (ortopedia, neurología, neurocirugía, EPS) con el diagnóstico de la remisión si se mencionó. No lo conviertas en diagnóstico propio ni agregues remitentes no dichos."},
    {"key":"enfermedad_actual_y_evolucion","label":"Enfermedad actual y evolución","order":2,"required":true,"instruction":"Cronología de la lesión o condición: inicio, mecanismo si lo hubo, evolución del dolor y de la limitación, cirugías o inmovilizaciones, terapias ya recibidas (física, ocupacional) y respuesta. Registra solo lo mencionado en la consulta; si algo no se abordó, indícalo."},
    {"key":"funcionalidad_previa","label":"Funcionalidad previa y contexto","order":3,"required":false,"instruction":"Nivel funcional antes del evento: marcha e independencia en actividades de la vida diaria, ayudas técnicas que ya usaba (bastón, caminador, silla de ruedas), ocupación y rol en casa. Incluye barreras del entorno (escaleras, baño) solo si se comentaron; no supongas el nivel previo."},
    {"key":"antecedentes_relevantes","label":"Antecedentes relevantes","order":4,"required":false,"instruction":"Antecedentes patológicos, quirúrgicos y farmacológicos que condicionan la rehabilitación (osteosíntesis, artroplastia, ECV, diabetes, osteoporosis), alergias y medicación actual tal como se enunció. Si no se interrogaron antecedentes, dilo expresamente en lugar de completarlos."},
    {"key":"revision_dirigida","label":"Revisión dirigida por sistemas","order":5,"required":false,"instruction":"Síntomas que modifican el plan: dolor en reposo o nocturno, espasticidad, parestesias, control de esfínteres, trastornos de deglución o del ánimo, caídas recientes. Solo los que se mencionaron; no marques sistemas como negativos si no se preguntaron."},
    {"key":"examen_fisico_funcional","label":"Examen físico funcional","order":6,"required":true,"instruction":"Inspección, fuerza por grupos musculares y tono tal como se dictaron (grado de fuerza solo si el médico enunció el valor), sensibilidad, reflejos, rangos articulares con las cifras dichas, marcha, balance y transferencias observadas. No completes segmentos no examinados ni estimes valores que no se dijeron."},
    {"key":"escalas_funcionales","label":"Escalas funcionales aplicadas","order":7,"required":false,"instruction":"Escalas únicamente si el médico las aplicó y dictó el puntaje (Barthel, FIM, Berg, fuerza MRC, EVA de dolor): transcribe el nombre y el puntaje literal, nunca los calcules ni los estimes tú. Si no se aplicó ninguna escala, indícalo."},
    {"key":"analisis_e_impresion_diagnostica","label":"Análisis e impresión diagnóstica","order":8,"required":true,"instruction":"Razonamiento del fisiatra: diagnóstico nosológico y diagnóstico funcional (limitaciones de actividad y restricciones de participación) con la precisión con que los formuló, incluidos los diferenciales que enunció. No agregues diagnósticos ni pronósticos que no se dijeron."},
    {"key":"plan_de_rehabilitacion_y_metas","label":"Plan de rehabilitación y metas funcionales","order":9,"required":true,"instruction":"Metas funcionales acordadas y plan formulado: terapias (física, ocupacional, fonoaudiología) con número de sesiones y frecuencia tal como se prescribieron, ayudas técnicas u órtesis, medicamentos con dosis literal, paraclínicos, remisiones e incapacidad si se expidió. Transcribe sesiones y dosis literal; no las ajustes ni completes."},
    {"key":"proximo_control_y_recomendaciones","label":"Próximo control y recomendaciones","order":10,"required":false,"instruction":"Cuándo vuelve a control y con qué (avances de terapia, imágenes), ejercicios o precauciones para la casa y signos de alarma explicados (aumento del dolor, déficit nuevo, caídas). Solo lo que se dijo al paciente o cuidador."}
  ]'::jsonb,
  updated_at = now()
where id = '22d41178-6556-5838-92cb-bbb5396f046e' and owner_id is null;

update public.clinical_templates set
  name = 'Control y seguimiento · metas funcionales y respuesta al plan',
  description = 'Control de fisiatría para pacientes ya en plan de rehabilitación: sesiones cumplidas, evolución funcional frente a las metas, tolerancia a la terapia y ajuste del plan. Úsala en cada seguimiento; no aplica para la primera valoración ni para procedimientos.',
  sections = '[
    {"key":"diagnosticos_y_tiempo_de_evolucion","label":"Diagnósticos activos y tiempo de evolución","order":1,"required":true,"instruction":"Diagnóstico nosológico y funcional por el que está en rehabilitación y tiempo de evolución o fecha del evento tal como se mencionaron. No actualices estadios ni clasificaciones que el médico no enunció hoy."},
    {"key":"intervalo_y_adherencia","label":"Intervalo y adherencia al plan","order":2,"required":false,"instruction":"Tiempo desde el último control, sesiones de terapia realizadas frente a las formuladas, adherencia al programa de ejercicios en casa y barreras referidas (autorización de la EPS, transporte, dolor). Solo lo que el paciente o el cuidador refirió."},
    {"key":"evolucion_funcional","label":"Evolución funcional referida","order":3,"required":true,"instruction":"Cambios que el paciente o el terapeuta reportan: marcha, transferencias, actividades de la vida diaria, dolor, uso de ayudas técnicas. Registra mejoría, estancamiento o retroceso solo en los términos en que se expresó; no cuantifiques avances que nadie midió."},
    {"key":"tolerancia_y_eventos","label":"Tolerancia y eventos adversos","order":4,"required":false,"instruction":"Tolerancia a la terapia y a los medicamentos: dolor durante o después de las sesiones, fatiga, caídas desde el último control, efectos adversos de la medicación (somnolencia, mareo). Si no se refirieron eventos, indícalo tal cual; no lo des por negativo si no se preguntó."},
    {"key":"examen_fisico_de_control","label":"Examen físico de control","order":5,"required":true,"instruction":"Examen dirigido a lo que se está rehabilitando: fuerza, tono, rangos articulares, marcha, balance y transferencias con los hallazgos y valores tal como se dictaron hoy. Compara con el control previo solo si el médico hizo la comparación; no completes lo no examinado."},
    {"key":"evaluacion_de_metas_y_escalas","label":"Evaluación de metas y escalas","order":6,"required":false,"instruction":"Estado de cada meta funcional planteada (lograda, en progreso, replanteada) según lo discutido, y escalas de seguimiento solo si se aplicaron hoy con puntaje dictado: transcríbelo literal, nunca lo calcules ni lo compares por tu cuenta."},
    {"key":"ajuste_del_plan","label":"Ajuste del plan de rehabilitación","order":7,"required":true,"instruction":"Decisiones de hoy: continuar, intensificar o modificar terapias con las sesiones y frecuencia tal como se formularon, cambios de medicación con dosis literal, nuevas ayudas técnicas u órtesis, remisiones, prórroga de incapacidad. No agregues conductas ni sesiones que no se prescribieron."},
    {"key":"proximo_control","label":"Próximo control y recomendaciones","order":8,"required":false,"instruction":"Fecha o plazo del próximo control, qué debe traer (avances del terapeuta, imágenes), ejercicios y precauciones en casa y signos para consultar antes. Solo lo indicado al paciente."}
  ]'::jsonb,
  updated_at = now()
where id = 'a93152f7-3a78-5a21-a051-05af418339b4' and owner_id is null;

update public.clinical_templates set
  name = 'Procedimiento · intervenciones en rehabilitación (infiltración, toxina botulínica)',
  description = 'Nota de procedimientos realizados por fisiatría: infiltraciones articulares o de tejidos blandos, aplicación de toxina botulínica para espasticidad, bloqueos. Documenta indicación, consentimiento, técnica, medicamentos con dosis literal, tolerancia e indicaciones posteriores.',
  sections = '[
    {"key":"indicacion_y_contexto","label":"Indicación y contexto clínico","order":1,"required":true,"instruction":"Diagnóstico que motiva el procedimiento y objetivo enunciado (dolor, espasticidad que limita función o higiene), tratamientos previos intentados y procedimientos anteriores con su respuesta, tal como se mencionaron. No justifiques la indicación con datos no dichos."},
    {"key":"verificacion_y_consentimiento","label":"Verificación previa y consentimiento informado","order":2,"required":false,"instruction":"Consentimiento informado explicado y firmado si así se dijo, verificación del sitio correcto, alergias interrogadas y anticoagulantes o condiciones revisadas antes del procedimiento. Registra solo las verificaciones que se enunciaron; si no se mencionaron, indícalo."},
    {"key":"tecnica_y_medicamentos","label":"Técnica, sitio y medicamentos aplicados","order":3,"required":true,"instruction":"Describe el procedimiento como lo narró el médico: sitio anatómico y lado, guía utilizada (ecografía, referencias anatómicas), aguja y técnica, y cada medicamento con dosis, concentración y unidades transcritas literal. Nunca calcules, conviertas ni completes una dosis que no se dictó."},
    {"key":"hallazgos_durante_el_procedimiento","label":"Hallazgos durante el procedimiento","order":4,"required":true,"instruction":"Hallazgos descritos durante la intervención: características del líquido si hubo artrocentesis, patrón de espasticidad, respuesta muscular a la estimulación si se usó, y cualquier variación de la técnica planeada. Solo lo que se narró; no describas hallazgos estándar por defecto."},
    {"key":"tolerancia_y_complicaciones","label":"Tolerancia y complicaciones inmediatas","order":5,"required":false,"instruction":"Cómo toleró el paciente el procedimiento y complicaciones inmediatas (dolor, sangrado, reacción vagal) únicamente si ocurrieron y se mencionaron. Si el médico dijo que no hubo complicaciones, regístralo en esos términos; no lo afirmes por tu cuenta."},
    {"key":"indicaciones_posteriores","label":"Indicaciones posteriores","order":6,"required":true,"instruction":"Cuidados indicados tras el procedimiento: reposo relativo o carga permitida, hielo, analgesia con dosis literal, signos por los que debe consultar (dolor que aumenta, fiebre, debilidad no esperada). Solo las indicaciones que se dieron al paciente o cuidador."},
    {"key":"plan_de_terapia_posterior","label":"Articulación con el plan de terapia","order":7,"required":false,"instruction":"Cómo se articula el procedimiento con la rehabilitación: cuándo reinicia o inicia terapia física u ocupacional, énfasis del trabajo posterior (estiramiento, fortalecimiento, órtesis) y metas esperadas, tal como lo planteó el médico. No agregues cronogramas no dichos."},
    {"key":"seguimiento","label":"Seguimiento y control","order":8,"required":false,"instruction":"Cuándo se evaluará la respuesta al procedimiento y con qué criterios (dolor, función, tono), y la cita de control indicada. Registra solo el plazo que se dijo; no propongas intervalos."}
  ]'::jsonb,
  updated_at = now()
where id = '05e3630a-8b63-54b0-84fd-d4908c653c50' and owner_id is null;

insert into public.clinical_templates
  (id, owner_id, name, description, specialty_code, specialty_name, scope, is_default, status, sections)
values
  ('c7000000-0000-4000-8000-000000000001', null,
   'Prescripción de plan terapéutico · terapia física y ocupacional con metas',
   'Formulación o renovación del plan de terapias (física, ocupacional, fonoaudiología): metas funcionales, sesiones y frecuencia, programa en casa, ayudas técnicas y trámites ante la EPS. Úsala cuando la cita gira alrededor de prescribir o renovar terapias, no de valorar por primera vez ni de controlar.',
   'rehabilitacion', 'Medicina física y rehabilitación', 'institutional', false, 'active',
   '[
     {"key":"diagnostico_y_condicion_actual","label":"Diagnóstico y condición funcional actual","order":1,"required":true,"instruction":"Diagnóstico de base y estado funcional del día: marcha, transferencias, actividades de la vida diaria, dolor y ayudas técnicas en uso, tal como se describieron en la consulta. No resumas con clasificaciones o porcentajes que el médico no enunció."},
     {"key":"trayectoria_en_rehabilitacion","label":"Trayectoria en rehabilitación","order":2,"required":false,"instruction":"Ciclos de terapia previos: cuántas sesiones recibió, dónde y con qué respuesta, según lo referido. Incluye por qué se renueva o se inicia el plan (avance, estancamiento, evento nuevo) solo en los términos discutidos."},
     {"key":"metas_funcionales","label":"Metas funcionales acordadas","order":3,"required":true,"instruction":"Metas planteadas con el paciente y su familia tal como se acordaron: qué actividad se busca recuperar o mantener, en qué plazo y cómo se medirá el avance si el médico lo definió. Transcribe las metas literal; no las conviertas en objetivos genéricos ni inventes plazos."},
     {"key":"prescripcion_terapia_fisica","label":"Prescripción de terapia física","order":4,"required":true,"instruction":"Terapia física formulada: número de sesiones, frecuencia semanal, modalidades y énfasis (fortalecimiento, marcha, balance, manejo del dolor) exactamente como se prescribió. Transcribe el número de sesiones literal; nunca lo ajustes ni sugieras modalidades no dichas."},
     {"key":"terapia_ocupacional_y_fonoaudiologia","label":"Terapia ocupacional y fonoaudiología","order":5,"required":false,"instruction":"Si se formularon, terapia ocupacional (actividades de la vida diaria, férulas, adaptaciones) y fonoaudiología (deglución, lenguaje) con sesiones y énfasis tal como se dictaron. Si no se prescribieron, indícalo; no las agregues por simetría con la terapia física."},
     {"key":"ayudas_tecnicas_y_ortesis","label":"Ayudas técnicas y órtesis","order":6,"required":false,"instruction":"Ayudas técnicas u órtesis prescritas o ajustadas (caminador, bastón, silla de ruedas, férulas, plantillas) con las especificaciones que el médico dictó y el trámite indicado para conseguirlas. Solo lo formulado hoy o lo que se dijo que continúa."},
     {"key":"programa_en_casa_y_educacion","label":"Programa en casa y educación","order":7,"required":false,"instruction":"Ejercicios o actividades para realizar en casa, precauciones (riesgo de caída, manejo de carga, cuidado de la piel en usuarios de silla de ruedas) y educación dada al paciente y su cuidador. Registra solo lo explicado en la consulta."},
     {"key":"tramites_y_soportes","label":"Trámites, remisiones e incapacidad","order":8,"required":false,"instruction":"Órdenes y soportes generados: remisiones, orden de terapias para autorización de la EPS, incapacidad o su prórroga con los días indicados, certificados. Transcribe los días de incapacidad literal; no los calcules."},
     {"key":"seguimiento_y_reevaluacion","label":"Seguimiento y criterios de reevaluación","order":9,"required":true,"instruction":"Cuándo se reevaluará el plan y con qué criterios (cumplimiento de metas, informe del terapeuta, nueva imagen), y qué haría ajustar o suspender las terapias, según lo dicho. No definas criterios de alta que el médico no mencionó."}
   ]'::jsonb)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  specialty_code = excluded.specialty_code,
  specialty_name = excluded.specialty_name,
  sections = excluded.sections,
  updated_at = now();

update public.clinical_templates set
  name = 'Consulta inicial · valoración integral de dolor y síntomas',
  description = 'Primera valoración por dolor y cuidados paliativos: enfermedad de base, caracterización del dolor y demás síntomas, esquema analgésico transcrito literal, esfera emocional y espiritual, y plan inicial. Úsala cuando el paciente llega remitido o consulta por primera vez al servicio.',
  sections = '[
    {"key":"motivo_y_remision","label":"Motivo de consulta y remisión","order":1,"required":true,"instruction":"Documenta el motivo en las palabras del paciente o su familia y quién remite (oncología, medicina interna, EPS) con el propósito enunciado de la remisión (control del dolor, manejo de síntomas, acompañamiento). No reformules el motivo como diagnóstico."},
    {"key":"enfermedad_de_base_y_tratamientos","label":"Enfermedad de base y tratamientos","order":2,"required":false,"instruction":"Enfermedad de base oncológica o no oncológica con el estadio o extensión solo en los términos en que el médico los enunció, tratamientos recibidos o en curso (quimioterapia, radioterapia, diálisis) y decisiones previas del equipo tratante. No completes estadios ni pronósticos no dichos."},
    {"key":"caracterizacion_del_dolor","label":"Caracterización del dolor","order":3,"required":true,"instruction":"Localización, irradiación y tipo de dolor solo si el médico lo tipificó (neuropático, somático, visceral), intensidad con la escala exactamente como se enunció (nunca asignes un puntaje tú), factores que lo agravan o alivian, dolor irruptivo y su frecuencia referida. Solo lo dicho en la consulta."},
    {"key":"otros_sintomas","label":"Otros síntomas","order":4,"required":false,"instruction":"Síntomas acompañantes referidos: náuseas, estreñimiento, disnea, fatiga, anorexia, insomnio, ansiedad, delirium. Si se aplicó una escala de síntomas con puntajes, transcríbelos literal; nunca los calcules. No marques síntomas como ausentes si no se preguntaron."},
    {"key":"esquema_analgesico_actual","label":"Esquema analgésico actual","order":5,"required":false,"instruction":"Medicamentos analgésicos y coadyuvantes en uso: nombre, dosis, vía, frecuencia y rescates transcritos LITERAL como se dictaron, incluidos opioides. Nunca calcules dosis equivalentes ni conversiones entre opioides ni completes una dosis que no se dijo. Anota adherencia y barreras de acceso referidas (EPS, disponibilidad)."},
    {"key":"funcionalidad_y_estado_general","label":"Funcionalidad y estado general","order":6,"required":false,"instruction":"Nivel de actividad y autonomía descritos: qué puede hacer, cuánto tiempo pasa en cama, dependencia para el autocuidado. Escalas de funcionalidad (ECOG, Karnofsky, PPS) únicamente si el médico las enunció con su valor: transcríbelo literal, nunca lo estimes tú."},
    {"key":"esfera_emocional_espiritual_y_red","label":"Esfera emocional, espiritual y red de apoyo","order":7,"required":false,"instruction":"Estado de ánimo, preocupaciones y sufrimiento expresados por el paciente, dimensión espiritual o religiosa si se abordó, cuidador principal y red de apoyo, y qué comprenden paciente y familia de la enfermedad. Usa lenguaje digno y textual; si la esfera no se exploró, indícalo sin juzgar."},
    {"key":"examen_fisico_dirigido","label":"Examen físico dirigido","order":8,"required":true,"instruction":"Hallazgos del examen tal como se dictaron: estado general y de conciencia, signos vitales con los valores dichos, hallazgos en los sitios de dolor, piel y zonas de presión, hidratación y estado nutricional descrito. No completes sistemas no examinados ni agregues valores."},
    {"key":"analisis_e_impresion_diagnostica","label":"Análisis e impresión diagnóstica","order":9,"required":true,"instruction":"Razonamiento del médico: síndromes dolorosos y problemas activos priorizados con la precisión con que los formuló, incluida la clasificación del dolor solo si él la enunció. Deja explícito lo que quedó pendiente de estudiar. No añadas diagnósticos ni pronósticos."},
    {"key":"plan_de_manejo_y_educacion","label":"Plan de manejo, educación y próximos pasos","order":10,"required":true,"instruction":"Plan formulado: cada medicamento con dosis, vía, frecuencia y rescates transcritos literal (nunca calcules conversiones de opioides), laxante profiláctico si se indicó, medidas no farmacológicas, paraclínicos, remisiones, conversación inicial de metas de cuidado si ocurrió, educación a la familia, próximo control y signos de alarma explicados."}
  ]'::jsonb,
  updated_at = now()
where id = '8dda35a4-8256-53ef-9216-ee9b198488ec' and owner_id is null;

update public.clinical_templates set
  name = 'Control y seguimiento · alivio del dolor y ajuste de analgesia',
  description = 'Seguimiento de pacientes ya en manejo por dolor y paliativos: respuesta a la analgesia, rescates usados, efectos adversos de opioides, síntomas y esfera emocional, con el ajuste del esquema transcrito literal. Úsala en cada control ambulatorio o domiciliario.',
  sections = '[
    {"key":"diagnosticos_y_contexto","label":"Diagnósticos activos y contexto","order":1,"required":true,"instruction":"Enfermedad de base y problemas activos en seguimiento (dolor, otros síntomas) con el tiempo de evolución tal como se mencionó, y dónde se atiende (consultorio, domicilio). No actualices estadios ni condiciones que hoy no se enunciaron."},
    {"key":"intervalo_adherencia_y_rescates","label":"Intervalo, adherencia y rescates","order":2,"required":false,"instruction":"Tiempo desde el último control, adherencia al esquema y número de rescates por día tal como el paciente o el cuidador lo refirió (transcríbelo literal, no lo promedies), y barreras: temor a los opioides, efectos adversos, autorización o disponibilidad en la EPS."},
    {"key":"evolucion_del_dolor_y_sintomas","label":"Evolución del dolor y de los síntomas","order":3,"required":true,"instruction":"Intensidad actual del dolor con la escala exactamente como se enunció (nunca asignes ni compares puntajes por tu cuenta), alivio percibido en palabras del paciente, dolor irruptivo y evolución de los demás síntomas (estreñimiento, náuseas, disnea, sueño, apetito). Solo lo referido hoy."},
    {"key":"efectos_adversos","label":"Efectos adversos y seguridad de opioides","order":4,"required":false,"instruction":"Efectos adversos referidos: estreñimiento, somnolencia, náuseas, prurito, mioclonías, confusión u otros signos que el médico atribuyó a la medicación, en sus términos. Si el médico dijo que no hay efectos adversos, regístralo así; no lo concluyas tú."},
    {"key":"esfera_emocional_y_red_de_apoyo","label":"Esfera emocional y red de apoyo","order":5,"required":false,"instruction":"Ánimo, preocupaciones y sobrecarga del cuidador expresados en la consulta, cambios en la red de apoyo y avances en las conversaciones sobre metas de cuidado si las hubo. Lenguaje digno y textual; si no se abordó, indícalo."},
    {"key":"examen_fisico_de_control","label":"Examen físico de control","order":6,"required":true,"instruction":"Examen dirigido del día: estado general y de conciencia, signos vitales con los valores dichos, hallazgos en los sitios de dolor, abdomen si se examinó por estreñimiento, piel y zonas de presión. No completes lo no examinado."},
    {"key":"ajuste_de_analgesia_y_plan","label":"Ajuste de la analgesia y plan","order":7,"required":true,"instruction":"Cambios del esquema tal como el médico los dictó: cada medicamento con dosis, vía, frecuencia y rescates transcritos LITERAL. Nunca calcules conversiones ni equivalencias de opioides ni completes una titulación: si el médico rotó un opioide, registra únicamente las cifras que él dictó. Incluye laxantes, coadyuvantes, paraclínicos y remisiones."},
    {"key":"proximo_control_y_alarma","label":"Próximo control y signos de alarma","order":8,"required":false,"instruction":"Plazo del próximo control o visita domiciliaria, a quién llamar si el dolor no cede, y los signos de alarma explicados (dolor no controlado con rescates, somnolencia marcada, vómito persistente, ausencia de deposición). Solo lo indicado hoy."}
  ]'::jsonb,
  updated_at = now()
where id = '806ea616-b522-5231-aa18-541410d664e2' and owner_id is null;

update public.clinical_templates set
  name = 'Procedimiento · intervencionismo analgésico y de confort',
  description = 'Nota de procedimientos del servicio: bloqueos nerviosos, infiltraciones, paracentesis o toracentesis de confort, manejo de dispositivos de infusión. Documenta indicación, consentimiento, técnica con dosis literal, tolerancia, ajuste del esquema e indicaciones posteriores.',
  sections = '[
    {"key":"indicacion_y_contexto_clinico","label":"Indicación y contexto clínico","order":1,"required":true,"instruction":"Diagnóstico y síntoma que motivan el procedimiento con el objetivo enunciado (aliviar dolor refractario, drenar para confort), intentos farmacológicos previos y su resultado, tal como se mencionaron. No justifiques la indicación con criterios que el médico no dijo."},
    {"key":"verificacion_y_consentimiento","label":"Verificación previa y consentimiento informado","order":2,"required":false,"instruction":"Consentimiento informado del paciente o su representante si así se dijo, explicación de riesgos, verificación del sitio, alergias y anticoagulación revisadas antes del procedimiento. Registra solo las verificaciones que se enunciaron; si no se mencionaron, indícalo."},
    {"key":"tecnica_y_medicamentos","label":"Técnica, sitio y medicamentos","order":3,"required":true,"instruction":"Describe el procedimiento como se narró: sitio anatómico y lado, guía utilizada (ecografía, fluoroscopia, referencias), técnica y cada medicamento con dosis, concentración y volumen transcritos LITERAL. Nunca calcules ni completes dosis, y nunca conviertas opioides entre vías: solo las cifras dictadas."},
    {"key":"hallazgos_y_respuesta_inmediata","label":"Hallazgos y respuesta inmediata","order":4,"required":true,"instruction":"Hallazgos durante la intervención (características y volumen del líquido drenado si se dijo, respuesta al bloqueo) y alivio inmediato referido por el paciente en sus palabras o con la escala solo como se enunció. No describas resultados esperados como si hubieran ocurrido."},
    {"key":"tolerancia_y_complicaciones","label":"Tolerancia y complicaciones inmediatas","order":5,"required":false,"instruction":"Tolerancia del paciente y complicaciones inmediatas (hipotensión, sangrado, dolor durante el procedimiento) solo si ocurrieron y se mencionaron. Si el médico dijo que no hubo complicaciones, regístralo en esos términos; no lo afirmes por defecto."},
    {"key":"indicaciones_posteriores","label":"Indicaciones posteriores","order":6,"required":true,"instruction":"Cuidados indicados después: reposo, vigilancia del sitio, curaciones, analgesia posprocedimiento con dosis literal y signos por los que la familia debe consultar (fiebre, sangrado, déficit nuevo, dolor que reaparece). Solo lo que se explicó al paciente o cuidador."},
    {"key":"ajuste_del_esquema_analgesico","label":"Ajuste del esquema analgésico","order":7,"required":false,"instruction":"Cambios del esquema derivados del procedimiento tal como se dictaron: suspensiones, reducciones o nuevas dosis transcritas literal. Nunca recalcules dosis por el efecto esperado del bloqueo ni hagas equivalencias de opioides; si el médico no ajustó nada, indícalo."},
    {"key":"seguimiento","label":"Seguimiento y control","order":8,"required":false,"instruction":"Cuándo y cómo se evaluará la respuesta (control presencial, llamada, visita domiciliaria) y qué criterios se seguirán (dolor, necesidad de rescates, reacumulación de líquido), según lo dicho. No propongas plazos propios."}
  ]'::jsonb,
  updated_at = now()
where id = 'cc18e22d-2015-5ad5-bd78-0b6e352efcce' and owner_id is null;

insert into public.clinical_templates
  (id, owner_id, name, description, specialty_code, specialty_name, scope, is_default, status, sections)
values
  ('c7000000-0000-4000-8000-000000000002', null,
   'Valoración de fin de vida · voluntades anticipadas y plan de confort',
   'Valoración del paciente en fase de fin de vida: síntomas predominantes, conversación de metas de cuidado con paciente y familia, voluntades anticipadas y adecuación del esfuerzo terapéutico, plan de confort farmacológico y no farmacológico y coordinación del cuidado en casa. Úsala cuando la consulta gira en torno al final de la vida, no para controles rutinarios.',
   'dolor_paliativos', 'Dolor y cuidados paliativos', 'institutional', false, 'active',
   '[
     {"key":"contexto_y_motivo","label":"Contexto y motivo de la valoración","order":1,"required":true,"instruction":"Situación que motiva la valoración (progresión de la enfermedad, deterioro reciente, solicitud de la familia o del equipo tratante), dónde se atiende al paciente y quiénes estuvieron presentes en la consulta. Solo lo mencionado; no describas el deterioro con datos no dichos."},
     {"key":"estado_actual_y_pronostico","label":"Estado actual y pronóstico enunciado","order":2,"required":false,"instruction":"Estado clínico descrito y pronóstico únicamente en los términos exactos en que el médico lo enunció a la familia. Nunca agregues plazos de sobrevida, estadios ni porcentajes que no se dijeron; si el pronóstico no se abordó, indícalo con respeto."},
     {"key":"sintomas_predominantes","label":"Síntomas predominantes","order":3,"required":true,"instruction":"Síntomas de la fase actual referidos: dolor con la escala solo como se enunció, disnea, secreciones, agitación o delirium, fiebre, imposibilidad para la vía oral. Describe la intensidad en las palabras usadas en la consulta; nunca asignes puntajes ni gravedad por tu cuenta."},
     {"key":"conciencia_de_enfermedad_y_comunicacion","label":"Conciencia de enfermedad y comunicación","order":4,"required":false,"instruction":"Qué comprenden el paciente (si pudo participar) y su familia de la situación, qué información se les dio hoy y cómo la recibieron, en lenguaje digno y textual. No atribuyas comprensión, acuerdo ni emociones que no se expresaron."},
     {"key":"metas_de_cuidado_y_voluntades","label":"Metas de cuidado y voluntades anticipadas","order":5,"required":true,"instruction":"Decisiones expresadas en la conversación: prioridad del confort, no reanimación, no traslado a UCI, límite o adecuación del esfuerzo terapéutico, documento de voluntad anticipada si existe o se diligenció, y quiénes participaron y estuvieron de acuerdo. Transcribe las decisiones tal como quedaron acordadas; jamás registres una decisión que no se expresó."},
     {"key":"plan_de_confort_farmacologico","label":"Plan de confort farmacológico","order":6,"required":true,"instruction":"Medicamentos del plan de confort con nombre, dosis, vía (incluida subcutánea o infusión) y frecuencia transcritos LITERAL como los dictó el médico, incluidos opioides y rescates. Nunca calcules conversiones ni equivalencias de opioides ni completes dosis. Si se indicó sedación paliativa, regístrala solo en los términos en que se indicó."},
     {"key":"cuidados_no_farmacologicos","label":"Cuidados no farmacológicos y del cuidador","order":7,"required":false,"instruction":"Medidas de confort explicadas: cuidado de la boca y la piel, cambios de posición, manejo de secreciones, alimentación e hidratación según lo conversado, y pautas dadas al cuidador. Solo las medidas que se explicaron en la consulta."},
     {"key":"esfera_emocional_y_espiritual","label":"Acompañamiento emocional y espiritual","order":8,"required":false,"instruction":"Sufrimiento emocional o espiritual expresado por el paciente y su familia, acompañamiento ofrecido (psicología, apoyo espiritual o religioso según sus creencias) y rituales o deseos manifestados. Lenguaje digno y textual; si no se abordó, indícalo sin juzgar."},
     {"key":"coordinacion_y_tramites","label":"Coordinación del cuidado y trámites","order":9,"required":false,"instruction":"Coordinación acordada: atención domiciliaria, disponibilidad de opioides y fórmulas para la EPS, insumos, certificados, a quién llamar y qué hacer llegado el fallecimiento en casa si se explicó. Solo lo efectivamente gestionado o indicado en la consulta."},
     {"key":"seguimiento_y_disponibilidad","label":"Seguimiento y disponibilidad del equipo","order":10,"required":false,"instruction":"Plan de seguimiento (visitas, llamadas), disponibilidad del equipo y signos esperables del final de la vida que se explicaron a la familia para anticipar sin alarmar. Registra solo lo que se explicó; no añadas listas estándar de signos."}
   ]'::jsonb)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  specialty_code = excluded.specialty_code,
  specialty_name = excluded.specialty_name,
  sections = excluded.sections,
  updated_at = now();
